/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {},
    },
    plugins: [],
    // Force include all classes
    safelist: [
        'bg-slate-50',
        'bg-slate-100',
        'bg-slate-200',
        'bg-slate-300',
        'bg-slate-600',
        'bg-slate-700',
        'bg-slate-800',
        'bg-slate-900',
        'text-slate-100',
        'text-slate-200',
        'text-slate-300',
        'text-slate-600',
        'text-slate-700',
        'text-slate-800',
        'border-slate-200',
        'border-slate-600',
        'border-slate-700',
        'hover:bg-slate-200',
        'hover:bg-slate-600',
        'hover:border-slate-300',
        'hover:border-slate-500',
        'rounded-full',
        'rounded-2xl',
        'backdrop-blur-sm',
        'backdrop-blur-md',
        'shadow-2xl',
        'from-slate-50',
        'to-gray-100',
        'from-slate-900',
        'to-gray-800',
    ],
}