// Currency data for GitHub Actions workflow
// This file can be used with require() in Node.js scripts

function getHardcodedCurrencies() {
    return [
        { code: 'USD', name: 'US Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/usd.static.svg' },
        { code: 'EUR', name: 'Euro', symbol: '€', flag: 'https://www.xe.com/svgs/flags/eur.static.svg' },
        { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', flag: 'https://www.xe.com/svgs/flags/cad.static.svg' },
        { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', flag: 'https://www.xe.com/svgs/flags/chf.static.svg' },
        { code: 'GBP', name: 'British Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/gbp.static.svg' },
        { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: 'https://www.xe.com/svgs/flags/aed.static.svg' },
        { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', flag: 'https://www.xe.com/svgs/flags/afn.static.svg' },
        { code: 'ALL', name: 'Albanian Lek', symbol: 'L', flag: 'https://www.xe.com/svgs/flags/all.static.svg' },
        { code: 'AMD', name: 'Armenian Dram', symbol: '֏', flag: 'https://www.xe.com/svgs/flags/amd.static.svg' },
        { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', flag: 'https://www.xe.com/svgs/flags/ang.static.svg' },
        { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', flag: 'https://www.xe.com/svgs/flags/aoa.static.svg' },
        { code: 'ARS', name: 'Argentine Peso', symbol: '$', flag: 'https://www.xe.com/svgs/flags/ars.static.svg' },
        { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', flag: 'https://www.xe.com/svgs/flags/aud.static.svg' },
        { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', flag: 'https://www.xe.com/svgs/flags/awg.static.svg' },
        { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', flag: 'https://www.xe.com/svgs/flags/azn.static.svg' },
        { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'КМ', flag: 'https://www.xe.com/svgs/flags/bam.static.svg' },
        { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/bbd.static.svg' },
        { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', flag: 'https://www.xe.com/svgs/flags/bdt.static.svg' },
        { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', flag: 'https://www.xe.com/svgs/flags/bgn.static.svg' },
        { code: 'BHD', name: 'Bahraini Dinar', symbol: 'د.ب', flag: 'https://www.xe.com/svgs/flags/bhd.static.svg' },
        { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', flag: 'https://www.xe.com/svgs/flags/bif.static.svg' },
        { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/bmd.static.svg' },
        { code: 'BND', name: 'Brunei Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/bnd.static.svg' },
        { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', flag: 'https://www.xe.com/svgs/flags/bob.static.svg' },
        { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', flag: 'https://www.xe.com/svgs/flags/brl.static.svg' },
        { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', flag: 'https://www.xe.com/svgs/flags/btn.static.svg' },
        { code: 'BWP', name: 'Botswana Pula', symbol: 'P', flag: 'https://www.xe.com/svgs/flags/bwp.static.svg' },
        { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', flag: 'https://www.xe.com/svgs/flags/byn.static.svg' },
        { code: 'BZD', name: 'Belize Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/bzd.static.svg' },
        { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', flag: 'https://www.xe.com/svgs/flags/cdf.static.svg' },
        { code: 'CLP', name: 'Chilean Peso', symbol: '$', flag: 'https://www.xe.com/svgs/flags/clp.static.svg' },
        { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: 'https://www.xe.com/svgs/flags/cny.static.svg' },
        { code: 'COP', name: 'Colombian Peso', symbol: '$', flag: 'https://www.xe.com/svgs/flags/cop.static.svg' },
        { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', flag: 'https://www.xe.com/svgs/flags/crc.static.svg' },
        { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', flag: 'https://www.xe.com/svgs/flags/czk.static.svg' },
        { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', flag: 'https://www.xe.com/svgs/flags/djf.static.svg' },
        { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', flag: 'https://www.xe.com/svgs/flags/dop.static.svg' },
        { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', flag: 'https://www.xe.com/svgs/flags/dzd.static.svg' },
        { code: 'EGP', name: 'Egyptian Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/egp.static.svg' },
        { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', flag: 'https://www.xe.com/svgs/flags/etb.static.svg' },
        { code: 'FJD', name: 'Fijian Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/fjd.static.svg' },
        { code: 'GEL', name: 'Georgian Lari', symbol: '₾', flag: 'https://www.xe.com/svgs/flags/gel.static.svg' },
        { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', flag: 'https://www.xe.com/svgs/flags/gtq.static.svg' },
        { code: 'GYD', name: 'Guyanese Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/gyd.static.svg' },
        { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', flag: 'https://www.xe.com/svgs/flags/hkd.static.svg' },
        { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', flag: 'https://www.xe.com/svgs/flags/hnl.static.svg' },
        { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', flag: 'https://www.xe.com/svgs/flags/hrk.static.svg' },
        { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', flag: 'https://www.xe.com/svgs/flags/huf.static.svg' },
        { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', flag: 'https://www.xe.com/svgs/flags/idr.static.svg' },
        { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', flag: 'https://www.xe.com/svgs/flags/ils.static.svg' },
        { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: 'https://www.xe.com/svgs/flags/inr.static.svg' },
        { code: 'IQD', name: 'Iraqi Dinar', symbol: 'د.ع', flag: 'https://www.xe.com/svgs/flags/iqd.static.svg' },
        { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', flag: 'https://www.xe.com/svgs/flags/irr.static.svg' },
        { code: 'JMD', name: 'Jamaican Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/jmd.static.svg' },
        { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', flag: 'https://www.xe.com/svgs/flags/jod.static.svg' },
        { code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: 'https://www.xe.com/svgs/flags/jpy.static.svg' },
        { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', flag: 'https://www.xe.com/svgs/flags/kes.static.svg' },
        { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с', flag: 'https://www.xe.com/svgs/flags/kgs.static.svg' },
        { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', flag: 'https://www.xe.com/svgs/flags/khr.static.svg' },
        { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', flag: 'https://www.xe.com/svgs/flags/kmf.static.svg' },
        { code: 'KRW', name: 'South Korean Won', symbol: '₩', flag: 'https://www.xe.com/svgs/flags/krw.static.svg' },
        { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', flag: 'https://www.xe.com/svgs/flags/kwd.static.svg' },
        { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/kyd.static.svg' },
        { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', flag: 'https://www.xe.com/svgs/flags/kzt.static.svg' },
        { code: 'LAK', name: 'Lao Kip', symbol: '₭', flag: 'https://www.xe.com/svgs/flags/lak.static.svg' },
        { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', flag: 'https://www.xe.com/svgs/flags/lbp.static.svg' },
        { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', flag: 'https://www.xe.com/svgs/flags/lkr.static.svg' },
        { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', flag: 'https://www.xe.com/svgs/flags/lsl.static.svg' },
        { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', flag: 'https://www.xe.com/svgs/flags/lyd.static.svg' },
        { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', flag: 'https://www.xe.com/svgs/flags/mad.static.svg' },
        { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', flag: 'https://www.xe.com/svgs/flags/mdl.static.svg' },
        { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', flag: 'https://www.xe.com/svgs/flags/mga.static.svg' },
        { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', flag: 'https://www.xe.com/svgs/flags/mkd.static.svg' },
        { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', flag: 'https://www.xe.com/svgs/flags/mnt.static.svg' },
        { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', flag: 'https://www.xe.com/svgs/flags/mop.static.svg' },
        { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', flag: 'https://www.xe.com/svgs/flags/mur.static.svg' },
        { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', flag: 'https://www.xe.com/svgs/flags/mvr.static.svg' },
        { code: 'MXN', name: 'Mexican Peso', symbol: '$', flag: 'https://www.xe.com/svgs/flags/mxn.static.svg' },
        { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', flag: 'https://www.xe.com/svgs/flags/myr.static.svg' },
        { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', flag: 'https://www.xe.com/svgs/flags/mzn.static.svg' },
        { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', flag: 'https://www.xe.com/svgs/flags/nio.static.svg' },
        { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', flag: 'https://www.xe.com/svgs/flags/nok.static.svg' },
        { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', flag: 'https://www.xe.com/svgs/flags/npr.static.svg' },
        { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', flag: 'https://www.xe.com/svgs/flags/nzd.static.svg' },
        { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', flag: 'https://www.xe.com/svgs/flags/omr.static.svg' },
        { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', flag: 'https://www.xe.com/svgs/flags/pab.static.svg' },
        { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', flag: 'https://www.xe.com/svgs/flags/pen.static.svg' },
        { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', flag: 'https://www.xe.com/svgs/flags/pgk.static.svg' },
        { code: 'PHP', name: 'Philippine Peso', symbol: '₱', flag: 'https://www.xe.com/svgs/flags/php.static.svg' },
        { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', flag: 'https://www.xe.com/svgs/flags/pkr.static.svg' },
        { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', flag: 'https://www.xe.com/svgs/flags/pln.static.svg' },
        { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', flag: 'https://www.xe.com/svgs/flags/qar.static.svg' },
        { code: 'RON', name: 'Romanian Leu', symbol: 'lei', flag: 'https://www.xe.com/svgs/flags/ron.static.svg' },
        { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', flag: 'https://www.xe.com/svgs/flags/rsd.static.svg' },
        { code: 'RUB', name: 'Russian Ruble', symbol: '₽', flag: 'https://www.xe.com/svgs/flags/rub.static.svg' },
        { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', flag: 'https://www.xe.com/svgs/flags/rwf.static.svg' },
        { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', flag: 'https://www.xe.com/svgs/flags/sar.static.svg' },
        { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', flag: 'https://www.xe.com/svgs/flags/sbd.static.svg' },
        { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', flag: 'https://www.xe.com/svgs/flags/scr.static.svg' },
        { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', flag: 'https://www.xe.com/svgs/flags/sdg.static.svg' },
        { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', flag: 'https://www.xe.com/svgs/flags/sek.static.svg' },
        { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', flag: 'https://www.xe.com/svgs/flags/sgd.static.svg' },
        { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/srd.static.svg' },
        { code: 'SYP', name: 'Syrian Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/syp.static.svg' },
        { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', flag: 'https://www.xe.com/svgs/flags/szl.static.svg' },
        { code: 'THB', name: 'Thai Baht', symbol: '฿', flag: 'https://www.xe.com/svgs/flags/thb.static.svg' },
        { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', flag: 'https://www.xe.com/svgs/flags/tjs.static.svg' },
        { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', flag: 'https://www.xe.com/svgs/flags/tmt.static.svg' },
        { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', flag: 'https://www.xe.com/svgs/flags/tnd.static.svg' },
        { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', flag: 'https://www.xe.com/svgs/flags/top.static.svg' },
        { code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: 'https://www.xe.com/svgs/flags/try.static.svg' },
        { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', flag: 'https://www.xe.com/svgs/flags/ttd.static.svg' },
        { code: 'TWD', name: 'Taiwan New Dollar', symbol: 'NT$', flag: 'https://www.xe.com/svgs/flags/twd.static.svg' },
        { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', flag: 'https://www.xe.com/svgs/flags/tzs.static.svg' },
        { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', flag: 'https://www.xe.com/svgs/flags/uah.static.svg' },
        { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', flag: 'https://www.xe.com/svgs/flags/ugx.static.svg' },
        { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', flag: 'https://www.xe.com/svgs/flags/uyu.static.svg' },
        { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S', flag: 'https://www.xe.com/svgs/flags/ves.static.svg' },
        { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', flag: 'https://www.xe.com/svgs/flags/vnd.static.svg' },
        { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', flag: 'https://www.xe.com/svgs/flags/vuv.static.svg' },
        { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', flag: 'https://www.xe.com/svgs/flags/wst.static.svg' },
        { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', flag: 'https://www.xe.com/svgs/flags/xaf.static.svg' },
        { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', flag: 'https://www.xe.com/svgs/flags/xcd.static.svg' },
        { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', flag: 'https://www.xe.com/svgs/flags/xof.static.svg' },
        { code: 'XPF', name: 'CFP Franc', symbol: '₣', flag: 'https://www.xe.com/svgs/flags/xpf.static.svg' },
        { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', flag: 'https://www.xe.com/svgs/flags/zmw.static.svg' },
        { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/bsd.static.svg' },
        { code: 'CUP', name: 'Cuban Peso', symbol: '$', flag: 'https://www.xe.com/svgs/flags/cup.static.svg' },
        { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', flag: 'https://www.xe.com/svgs/flags/cve.static.svg' },
        { code: 'DKK', name: 'Danish Krone', symbol: 'kr', flag: 'https://www.xe.com/svgs/flags/dkk.static.svg' },
        { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', flag: 'https://www.xe.com/svgs/flags/ern.static.svg' },
        { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/fkp.static.svg' },
        { code: 'GGP', name: 'Guernsey Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/ggp.static.svg' },
        { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', flag: 'https://www.xe.com/svgs/flags/ghs.static.svg' },
        { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/gip.static.svg' },
        { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', flag: 'https://www.xe.com/svgs/flags/gmd.static.svg' },
        { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', flag: 'https://www.xe.com/svgs/flags/gnf.static.svg' },
        { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', flag: 'https://www.xe.com/svgs/flags/htg.static.svg' },
        { code: 'IMP', name: 'Isle of Man Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/imp.static.svg' },
        { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', flag: 'https://www.xe.com/svgs/flags/isk.static.svg' },
        { code: 'JEP', name: 'Jersey Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/jep.static.svg' },
        { code: 'LRD', name: 'Liberian Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/lrd.static.svg' },
        { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', flag: 'https://www.xe.com/svgs/flags/mmk.static.svg' },
        { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', flag: 'https://www.xe.com/svgs/flags/mru.static.svg' },
        { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', flag: 'https://www.xe.com/svgs/flags/mwk.static.svg' },
        { code: 'NAD', name: 'Namibian Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/nad.static.svg' },
        { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: 'https://www.xe.com/svgs/flags/ngn.static.svg' },
        { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', flag: 'https://www.xe.com/svgs/flags/pyg.static.svg' },
        { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', flag: 'https://www.xe.com/svgs/flags/shp.static.svg' },
        { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', flag: 'https://www.xe.com/svgs/flags/sle.static.svg' },
        { code: 'SLL', name: 'Sierra Leonean Leone (Old)', symbol: 'Le', flag: 'https://www.xe.com/svgs/flags/sll.static.svg' },
        { code: 'SOS', name: 'Somali Shilling', symbol: 'S', flag: 'https://www.xe.com/svgs/flags/sos.static.svg' },
        { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', flag: 'https://www.xe.com/svgs/flags/stn.static.svg' },
        { code: 'TVD', name: 'Tuvaluan Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/tvd.static.svg' },
        { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв', flag: 'https://www.xe.com/svgs/flags/uzs.static.svg' },
        { code: 'XCG', name: 'East Caribbean Dollar (Old)', symbol: 'EC$', flag: 'https://www.xe.com/svgs/flags/xcg.static.svg' },
        { code: 'XDR', name: 'Special Drawing Rights', symbol: 'SDR', flag: 'https://www.xe.com/svgs/flags/xdr.static.svg' },
        { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', flag: 'https://www.xe.com/svgs/flags/yer.static.svg' },
        { code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: 'https://www.xe.com/svgs/flags/zar.static.svg' },
        { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '$', flag: 'https://www.xe.com/svgs/flags/zwl.static.svg' }
    ];
}

module.exports = { getHardcodedCurrencies };

